---
grails:
    profile: web
    codegen:
        defaultPackage: sx.integracion.rx
    gorm:
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false
dataSource:
      pooled: true
      driverClassName: com.mysql.jdbc.Driver
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      username: root

environments:
    development:
       dataSource:
         dbCreate: none
         url: jdbc:mysql://papel.dyndns-remote.com:3306/siipapx?autoReconnect=false
         password: sys
         properties:
           maxActive: 20
           maxIdle: 20
           minIdle: 2
           initialSize: 1
           minEvictableIdleTimeMillis: 1800000
           timeBetweenEvictionRunsMillis: 1800000
           numTestsPerEvictionRun: 3
           testOnBorrow: true
           testWhileIdle: true
           testOnReturn: true
           maxWait: 10000
           validationQuery: 'SELECT 1'
           validationQueryTimeout: 3
           validationInterval: 15000
    test:
        dataSource:
            dbCreate: none
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
           dbCreate: none
           url: jdbc:mysql://10.10.1.229/siipapx?autoReconnect=false
           password: sys
           properties:
             maxActive: 20
             maxIdle: 20
             minIdle: 2
             initialSize: 1
             minEvictableIdleTimeMillis: 1800000
             timeBetweenEvictionRunsMillis: 1800000
             numTestsPerEvictionRun: 3
             testOnBorrow: true
             testWhileIdle: true
             testOnReturn: true
             maxWait: 10000
             validationQuery: 'SELECT 1'
             validationQueryTimeout: 3
             validationInterval: 15000
---
quartz:
    autoStartup: false
---
server:
  port: 9080
  contextPath: /integracionRx
---


    